### ISSUE TITLE
Error Icon ubuntu

### ISSUE THREAD

**Issue by luigimassa** [moka-project/mokaproject.com#5]
Hi, 
icon in man tool bar are not good. it's possible to use ubuntu theme?
thanks

ps: I donate via paypal

![spazio di lavoro 1_100](https://cloud.githubusercontent.com/assets/186556/5599513/53454aa4-92c8-11e4-8add-251bb9bcdbc3.jpg)

**Comment by snwh** [comment]
This would be a GTK theme issue not a icon error.

**Comment by snwh** [comment]
The panel icons are part of the ```faba-mono-icons``` pack.
